spring.application.name=digital-fir1

spring.datasource.url=jdbc:mysql://dfs.cnmkuioqcyq8.ap-south-1.rds.amazonaws.com:3306/digital_fir?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}

file.upload-dir=uploads

